### PR TITLE
Use ErrorListener for better error handling

### LINKED ISSUE #8: Handle missing newlines or trailing spaces at end of file
I think the parser currently fails if the last line in the feature file does not end with a newline. There are two possible solutions:

 - Change the grammar to handle `EOF` same as `EOL` when the token can appear at the end of the file
 - Wrap the reader so that it automatically appends a missing `EOL` at the end of the file

### PR DESCRIPTION
**Pull request by jhorstmann**
This does not fix #8, but at least you'd get a proper error message.

Based on https://stackoverflow.com/a/26573239/139595

### CODE REVIEW

File: zuchini-model/src/main/java/org/zuchini/parser/FeatureParser.java [hunk 1]
```diff
@@ -69,13 +69,15 @@ static Feature parseWithWalker(ANTLRInputStream inputStream) {
     }
```
Comment (lukasniemeier-zalando) [inline zuchini-model/src/main/java/org/zuchini/parser/FeatureParser.java:69]: Is `parseWithWalker` used?

File: zuchini-model/src/main/java/org/zuchini/parser/FeatureParser.java [hunk 2]
```diff
@@ -69,13 +69,15 @@ static Feature parseWithWalker(ANTLRInputStream inputStream) {
...
-        return newParser(inputStream).feature().accept(new Visitors.FeatureVisitor(inputStream.getSourceName()));
+        GherkinParser.FeatureContext feature = newParser(inputStream).feature();
+        return feature.accept(new Visitors.FeatureVisitor(inputStream.getSourceName()));
     }
 
     static GherkinParser newParser(ANTLRInputStream inputStream) {
         GherkinLexer lexer = new GherkinLexer(inputStream);
         GherkinParser parser = new GherkinParser(new BufferedTokenStream(lexer));
-        parser.setErrorHandler(new BailErrorStrategy());
+        parser.removeErrorListeners();
```
Comment (lukasniemeier-zalando) [inline zuchini-model/src/main/java/org/zuchini/parser/FeatureParser.java]: Why remove the default (console) logger?

File: zuchini-model/src/main/java/org/zuchini/parser/ThrowingErrorListener.java [hunk 3]
```diff
@@ -0,0 +1,17 @@
...
+import org.antlr.v4.runtime.misc.ParseCancellationException;
+
+class ThrowingErrorListener extends BaseErrorListener {
+
+    public static final ThrowingErrorListener INSTANCE = new ThrowingErrorListener();
+
+    @Override
+    public void syntaxError(Recognizer<?, ?> recognizer, Object offendingSymbol, int line, int charPositionInLine, String msg, RecognitionException e)
+            throws ParseCancellationException {
+        throw new ParseCancellationException("line " + line + ":" + charPositionInLine + " " + msg);
```
Comment (lukasniemeier-zalando) [inline zuchini-model/src/main/java/org/zuchini/parser/ThrowingErrorListener.java]: Wrap the `RecognitionException`?

File: zuchini-model/src/main/java/org/zuchini/parser/FeatureParser.java (hunk 1 above)
Comment (jhorstmann) [reply zuchini-model/src/main/java/org/zuchini/parser/FeatureParser.java:69]: No :)

I kept it because the project actually started as me trying out writing parsers with antl4 and still could not decide which approach I like better.

File: zuchini-model/src/main/java/org/zuchini/parser/FeatureParser.java (hunk 2 above)
Comment (jhorstmann) [reply zuchini-model/src/main/java/org/zuchini/parser/FeatureParser.java]: The same message will be contained in the new exception, user should be responsible for logging or reacting on this.

File: zuchini-model/src/main/java/org/zuchini/parser/ThrowingErrorListener.java (hunk 3 above)
Comment (jhorstmann) [reply zuchini-model/src/main/java/org/zuchini/parser/ThrowingErrorListener.java]: Just tried this to see if there is useful information in there, but it turns out the exception parameter is actually `null` for the missing `EOL` use case. Maybe it will be set for other errors.

**Comment by lukasniemeier-zalando** [comment]
:+1:
